// src/lib/constants.ts - Shared constants for registration

export const SPORTS = [
  { value: 'futsal', label: 'Futsal', icon: '⚽' },
  { value: 'basketball', label: 'Basketball', icon: '🏀' },
  { value: 'volleyball', label: 'Volleyball', icon: '🏐' },
  { value: 'badminton', label: 'Badminton', icon: '🏸' },
  { value: 'tennis', label: 'Tennis', icon: '🎾' },
  { value: 'cricket', label: 'Cricket', icon: '🏏' }
];

export const SKILL_LEVELS = [
  { value: 'beginner', label: 'Beginner', icon: '🌱' },
  { value: 'intermediate', label: 'Intermediate', icon: '⚡' },
  { value: 'advanced', label: 'Advanced', icon: '🔥' },
  { value: 'professional', label: 'Professional', icon: '🏆' }
];

export const COUNTRIES = [
  { name: 'Nepal', code: '+977', flag: '🇳🇵', mask: '+977 ########' },
  { name: 'India', code: '+91', flag: '🇮🇳', mask: '+91 ##########' },
  { name: 'United States', code: '+1', flag: '🇺🇸', mask: '+1 (###) ###-####' },
  { name: 'United Kingdom', code: '+44', flag: '🇬🇧', mask: '+44 #### ######' },
  { name: 'Canada', code: '+1', flag: '🇨🇦', mask: '+1 (###) ###-####' },
  { name: 'Australia', code: '+61', flag: '🇦🇺', mask: '+61 ### ### ###' },
  { name: 'Germany', code: '+49', flag: '🇩🇪', mask: '+49 ### ########' },
  { name: 'France', code: '+33', flag: '🇫🇷', mask: '+33 # ## ## ## ##' },
  { name: 'Japan', code: '+81', flag: '🇯🇵', mask: '+81 ##-####-####' },
  { name: 'China', code: '+86', flag: '🇨🇳', mask: '+86 ### #### ####' },
  { name: 'South Korea', code: '+82', flag: '🇰🇷', mask: '+82 ##-####-####' },
  { name: 'Singapore', code: '+65', flag: '🇸🇬', mask: '+65 #### ####' },
  { name: 'Malaysia', code: '+60', flag: '🇲🇾', mask: '+60 ##-### ####' },
  { name: 'Thailand', code: '+66', flag: '🇹🇭', mask: '+66 ## ### ####' },
  { name: 'Philippines', code: '+63', flag: '🇵🇭', mask: '+63 ### ### ####' },
  { name: 'Indonesia', code: '+62', flag: '🇮🇩', mask: '+62 ###-###-####' },
  { name: 'Vietnam', code: '+84', flag: '🇻🇳', mask: '+84 ### ### ####' },
  { name: 'Bangladesh', code: '+880', flag: '🇧🇩', mask: '+880 ####-######' },
  { name: 'Pakistan', code: '+92', flag: '🇵🇰', mask: '+92 ### #######' },
  { name: 'Sri Lanka', code: '+94', flag: '🇱🇰', mask: '+94 ## ### ####' },
  { name: 'UAE', code: '+971', flag: '🇦🇪', mask: '+971 ## ### ####' },
  { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦', mask: '+966 ## ### ####' },
  { name: 'Qatar', code: '+974', flag: '🇶🇦', mask: '+974 #### ####' },
  { name: 'Kuwait', code: '+965', flag: '🇰🇼', mask: '+965 #### ####' },
  { name: 'Bahrain', code: '+973', flag: '🇧🇭', mask: '+973 #### ####' },
  { name: 'Oman', code: '+968', flag: '🇴🇲', mask: '+968 #### ####' },
  { name: 'Brazil', code: '+55', flag: '🇧🇷', mask: '+55 ## #####-####' },
  { name: 'Argentina', code: '+54', flag: '🇦🇷', mask: '+54 ## ####-####' },
  { name: 'Mexico', code: '+52', flag: '🇲🇽', mask: '+52 ## #### ####' },
  { name: 'South Africa', code: '+27', flag: '🇿🇦', mask: '+27 ## ### ####' },
  { name: 'Egypt', code: '+20', flag: '🇪🇬', mask: '+20 ## #### ####' },
  { name: 'Nigeria', code: '+234', flag: '🇳🇬', mask: '+234 ### ### ####' },
  { name: 'Kenya', code: '+254', flag: '🇰🇪', mask: '+254 ### ### ###' },
  { name: 'Ghana', code: '+233', flag: '🇬🇭', mask: '+233 ## ### ####' },
  { name: 'Morocco', code: '+212', flag: '🇲🇦', mask: '+212 ##-####-####' },
  { name: 'Tunisia', code: '+216', flag: '🇹🇳', mask: '+216 ## ### ###' },
  { name: 'Algeria', code: '+213', flag: '🇩🇿', mask: '+213 ## ### ####' },
  { name: 'Turkey', code: '+90', flag: '🇹🇷', mask: '+90 ### ### ####' },
  { name: 'Russia', code: '+7', flag: '🇷🇺', mask: '+7 ### ###-##-##' },
  { name: 'Italy', code: '+39', flag: '🇮🇹', mask: '+39 ### ### ####' },
  { name: 'Spain', code: '+34', flag: '🇪🇸', mask: '+34 ### ## ## ##' },
  { name: 'Netherlands', code: '+31', flag: '🇳🇱', mask: '+31 # #### ####' },
  { name: 'Belgium', code: '+32', flag: '🇧🇪', mask: '+32 ### ## ## ##' },
  { name: 'Switzerland', code: '+41', flag: '🇨🇭', mask: '+41 ## ### ## ##' },
  { name: 'Austria', code: '+43', flag: '🇦🇹', mask: '+43 ### ######' },
  { name: 'Sweden', code: '+46', flag: '🇸🇪', mask: '+46 ##-### ## ##' },
  { name: 'Norway', code: '+47', flag: '🇳🇴', mask: '+47 ### ## ###' },
  { name: 'Denmark', code: '+45', flag: '🇩🇰', mask: '+45 ## ## ## ##' },
  { name: 'Finland', code: '+358', flag: '🇫🇮', mask: '+358 ## ### ####' },
  { name: 'Poland', code: '+48', flag: '🇵🇱', mask: '+48 ### ### ###' },
  { name: 'Czech Republic', code: '+420', flag: '🇨🇿', mask: '+420 ### ### ###' },
  { name: 'Hungary', code: '+36', flag: '🇭🇺', mask: '+36 ## ### ####' },
  { name: 'Romania', code: '+40', flag: '🇷🇴', mask: '+40 ### ### ###' },
  { name: 'Bulgaria', code: '+359', flag: '🇧🇬', mask: '+359 ### ### ###' },
  { name: 'Croatia', code: '+385', flag: '🇭🇷', mask: '+385 ## ### ####' },
  { name: 'Serbia', code: '+381', flag: '🇷🇸', mask: '+381 ## ### ####' },
  { name: 'Slovenia', code: '+386', flag: '🇸🇮', mask: '+386 ## ### ###' },
  { name: 'Slovakia', code: '+421', flag: '🇸🇰', mask: '+421 ### ### ###' },
  { name: 'Estonia', code: '+372', flag: '🇪🇪', mask: '+372 #### ####' },
  { name: 'Latvia', code: '+371', flag: '🇱🇻', mask: '+371 #### ####' },
  { name: 'Lithuania', code: '+370', flag: '🇱🇹', mask: '+370 ### #####' },
  { name: 'Ukraine', code: '+380', flag: '🇺🇦', mask: '+380 ## ### ####' },
  { name: 'Belarus', code: '+375', flag: '🇧🇾', mask: '+375 ## ###-##-##' },
  { name: 'Moldova', code: '+373', flag: '🇲🇩', mask: '+373 #### ####' },
  { name: 'Georgia', code: '+995', flag: '🇬🇪', mask: '+995 ### ### ###' },
  { name: 'Armenia', code: '+374', flag: '🇦🇲', mask: '+374 ## ######' },
  { name: 'Azerbaijan', code: '+994', flag: '🇦🇿', mask: '+994 ## ### ####' },
  { name: 'Kazakhstan', code: '+7', flag: '🇰🇿', mask: '+7 ### ###-##-##' },
  { name: 'Uzbekistan', code: '+998', flag: '🇺🇿', mask: '+998 ## ### ####' },
  { name: 'Kyrgyzstan', code: '+996', flag: '🇰🇬', mask: '+996 ### ### ###' },
  { name: 'Tajikistan', code: '+992', flag: '🇹🇯', mask: '+992 ## ### ####' },
  { name: 'Turkmenistan', code: '+993', flag: '🇹🇲', mask: '+993 ## ### ###' },
  { name: 'Mongolia', code: '+976', flag: '🇲🇳', mask: '+976 ## ## ####' },
  { name: 'Afghanistan', code: '+93', flag: '🇦🇫', mask: '+93 ## ### ####' },
  { name: 'Iran', code: '+98', flag: '🇮🇷', mask: '+98 ### ### ####' },
  { name: 'Iraq', code: '+964', flag: '🇮🇶', mask: '+964 ### ### ####' },
  { name: 'Syria', code: '+963', flag: '🇸🇾', mask: '+963 ### ### ###' },
  { name: 'Lebanon', code: '+961', flag: '🇱🇧', mask: '+961 ## ### ###' },
  { name: 'Jordan', code: '+962', flag: '🇯🇴', mask: '+962 # #### ####' },
  { name: 'Israel', code: '+972', flag: '🇮🇱', mask: '+972 ##-###-####' },
  { name: 'Palestine', code: '+970', flag: '🇵🇸', mask: '+970 ## ### ####' },
  { name: 'Cyprus', code: '+357', flag: '🇨🇾', mask: '+357 ## ######' },
  { name: 'Malta', code: '+356', flag: '🇲🇹', mask: '+356 #### ####' },
  { name: 'Iceland', code: '+354', flag: '🇮🇸', mask: '+354 ### ####' },
  { name: 'Ireland', code: '+353', flag: '🇮🇪', mask: '+353 ## ### ####' },
  { name: 'Portugal', code: '+351', flag: '🇵🇹', mask: '+351 ### ### ###' },
  { name: 'Greece', code: '+30', flag: '🇬🇷', mask: '+30 ### ### ####' },
  { name: 'Albania', code: '+355', flag: '🇦🇱', mask: '+355 ## ### ####' },
  { name: 'North Macedonia', code: '+389', flag: '🇲🇰', mask: '+389 ## ### ###' },
  { name: 'Montenegro', code: '+382', flag: '🇲🇪', mask: '+382 ## ### ###' },
  { name: 'Bosnia and Herzegovina', code: '+387', flag: '🇧🇦', mask: '+387 ## ### ###' },
  { name: 'Kosovo', code: '+383', flag: '🇽🇰', mask: '+383 ## ### ###' }
];
