# src/main/resources/application.yml
chat:
  redis:
    enabled: false         # <— run fine without Redis in dev
    channel: chat-messages

rate limit:
  enabled: true
  perSecond: 10

spring:
  redis:
    host: localhost
    port: 6379
    # password: yourpass # if you set one


xai:
  enabled: true

security:
  jwt:
    secret: "change-me-32+chars-or-base64-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    issuer: pickup sports
    audience: web             # any label you check on both sides
    expirationMinutes: 60
    clockSkewSeconds: 120
    header: Authorization   # <- used in CONNECT headers
    prefix: "Bearer "       # <- removed when parsing


