# Staging profile configuration

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

# Staging-safe platform defaults
spring:
  jpa:
    hibernate:
      ddl-auto: validate   # avoid create/drop in staging
  websocket:
    enabled: true          # ensure WS stack is on in staging

chat:
  redis:
    enabled: true

# JWT for staging (override via env SECURITY_JWT_SECRET)
security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:bLzOR2h96wI6A3WyOoK_AsZaZqYawJmm5FWLEDCmDikMMMdmEdWLTEhFBC05bWi1}
    issuer: pickup-sports-app
    audience: pickup-sports-clients
    expiration-minutes: 120
    header: Authorization
    prefix: "Bearer "

# CORS staging example (adjust for your staging frontend)
app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:8080,http://localhost:8081,http://localhost:8082,https://staging.your-frontend.example.com"
    allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
    allowed-headers: "*"
    exposed-headers: "Authorization,Content-Type"
    allow-credentials: true

logging:
  pattern:
    level: "%5p [%X{requestId}]"

