# src/main/resources/application.yml
chat:
  redis:
    enabled: false         # <— run fine without Redis in dev
    channel: chat-messages
  ratelimit:
    enabled: true
    perSecond: 10

spring:
  redis:
    host: localhost
    port: 6379
    # password: yourpass # if you set one


xai:
  enabled: true

security:
  jwt:
    secret: "this-is-my-local-dev-secret-change-me"
    issuer: "pickup-sports-app"
    audience: "pickup-sports-clients"
    expirationMinutes: 120
    header: "Authorization"
    prefix: "Bearer "

# application-prod.yml
springdoc:
  swagger-ui.enabled: false
  api-docs.enabled: false


