# src/main/resources/application.yml
chat:
  redis:
    enabled: false         # <— run fine without Redis in dev
    channel: chat-messages

rate limit:
  enabled: true
  perSecond: 10

spring:
  redis:
    host: localhost
    port: 6379
    # password: yourpass # if you set one


xai:
  enabled: true

