# Dev-only OpenAPI/Swagger
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

# Actuator exposure in dev
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always
# Dev profile defaults
server:
  forward-headers-strategy: framework

# Disable real Web Push in dev (uses NoopWebPushClient)
push:
  webpush:
    enabled: false
  vapid:
    # Optional: supply keys when testing real Web Push
    # public-key:
    # private-key:
    subject: "mailto:admin@example.com"

# Use geospatial fallback when PostGIS isn't available
geo:
  postgis:
    force-fallback: true

# Short dedupe window for notifications in dev
notifications:
  dedupe:
    seconds: 30

# Admin MFA policy defaults
auth:
  login:
    require-mfa-for-admin: true
    admin-mfa-alert-window-minutes: 60

# Spring specifics (optional Redis – app runs fine without it)
# spring:
#   data:
#     redis:
#       host: localhost
#       port: 6379
# WebSocket/chat dev behavior
chat:
  redis:
    enabled: false

# CORS for local React dev server
app:
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
    allowed-headers: "*"
    exposed-headers: "Authorization,Content-Type"
    allow-credentials: false

logging:
  pattern:
    level: "%5p [%X{requestId}]"
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    com.bmessi.pickupsportsapp: DEBUG

