# src/main/resources/application.yml
chat:
  redis:
    enabled: false         # <— run fine without Redis in dev
    channel: chat-messages
  ratelimit:
    enabled: true
    perSecond: 10
    userBurst: 20
    userBurstWindowMillis: 10000
  subscription:
    max: 50
  moderation:
    enabled: true
    reject: false
    words: ["badword"]
    # dictionaryPath: "classpath:moderation/profanity.txt"

spring:
  redis:
    host: localhost
    port: 6379
    # password: yourpass # if you set one

xai:
  enabled: true

security:
  jwt:
    secret: "this-is-my-local-dev-secret-change-me"
    issuer: "pickup-sports-app"
    audience: "pickup-sports-clients"
    expirationMinutes: 120
    header: "Authorization"
    prefix: "Bearer "

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "never"   # set 'always' if you want details in dev
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  server:
    base-path: /actuator      # default, explicit for clarity

# Swagger/OpenAPI enabled in dev
springdoc:
  swagger-ui.enabled: true
  api-docs.enabled: true

resilience4j:
  retry:
    instances:
      xai:
        max-attempts: 3
        wait-duration: 200ms
      mail:
        max-attempts: 3
        wait-duration: 500ms
  timelimiter:
    instances:
      xai:
        timeout-duration: 2s
  ratelimiter:
    instances:
      xai:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 0
      auth:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 0
      chat:
        limit-for-period: 20
        limit-refresh-period: 1s
        timeout-duration: 0

# ------------------------------
# App configuration (new defaults)
# ------------------------------
auth:
  verification-required: false
  verification-ttl-hours: 24
  reset-ttl-hours: 2
  app-url: "http://localhost:8080"
  change-email-invalidate-sessions: true
  resend:
    max-per-user-per-minute: 3
    max-per-ip-per-minute: 10
  login:
    distributed-enabled: false
    max-failures-per-user: 5
    max-failures-per-ip: 30
    lockout-minutes: 15
    ip-window-minutes: 10
  rate-limit:
    distributed:
      enabled: false
    window-seconds: 60

media:
  avatar:
    max-bytes: 2097152
    allowed-types: "image/png,image/jpeg,image/webp"
    thumbnail:
      enabled: true
      width: 200
      height: 200
    max-width: 2000
    max-height: 2000
    absolute-max-width: 8000
    absolute-max-height: 8000
    strip-metadata: true
    include-thumbnail-header: false

app:
  media:
    storage:
      provider: local
    s3:
      bucket: your-bucket
      region: us-east-1
      endpoint:
      prefix:
      public-base-url:
      presign:
        enabled: false
        ttlSeconds: 900

retention:
  chat:
    messages:
      days: 60
    read-receipts:
      days: 60


