ALTER TABLE push_outbox
    ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS dead_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS dead_reason VARCHAR(255);
