global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "/etc/prometheus/rsvp-alert.rules.yml"
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'pickup-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']
