global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Application Metrics
  - job_name: 'pickup-sports-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['app:8080']
    basic_auth:
      username: ''
      password: ''

  # PostgreSQL Database (via exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # RabbitMQ Metrics  
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['pickup_rabbitmq:15692']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis Metrics (via exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 30s