spring:
  profiles:
    active: staging

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

chat:
  redis:
    enabled: true

# CORS staging example (adjust for your staging frontend)
app:
  cors:
    allowed-origins: "http://localhost:3000,https://staging.your-frontend.example.com"
    allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
    allowed-headers: "*"
    exposed-headers: "Authorization,Content-Type"
    allow-credentials: true

logging:
  pattern:
    level: "%5p [%X{requestId}]"

