resilience4j:
  retry:
    instances:
      xai:
        max-attempts: 3
        wait-duration: 200ms
  timelimiter:
    instances:
      xai:
        timeout-duration: 2s
  ratelimiter:
    instances:
      xai:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 0
  circuitbreaker:
    instances:
      xai:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
