CREATE TABLE IF NOT EXISTS user_notification_prefs (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES app_user(id),
    in_app_on_rsvp BOOLEAN NOT NULL DEFAULT TRUE,
    in_app_on_create BOOLEAN NOT NULL DEFAULT TRUE,
    in_app_on_cancel BOOLEAN NOT NULL DEFAULT TRUE,
    email_on_rsvp BOOLEAN NOT NULL DEFAULT TRUE,
    email_on_create BOOLEAN NOT NULL DEFAULT TRUE,
    email_on_cancel BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
