CREATE TABLE IF NOT EXISTS push_subscription (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    endpoint VARCHAR(1000) NOT NULL UNIQUE,
    p256dh VARCHAR(255),
    auth VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
