ALTER TABLE user_notification_prefs
    ADD COLUMN IF NOT EXISTS push_on_rsvp BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS push_on_create BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS push_on_cancel BOOLEAN NOT NULL DEFAULT TRUE;
